version: 2
jobs:
   build:
     working_directory: ~/thrive
     docker:
       - image: hhyyrylainen/leviathan-deps:v7
     environment:
       GIT_LFS_SKIP_SMUDGE: 1
     steps:
       - checkout
       - restore_cache:
           keys:
             - v2-lfs-{{ .Branch }}
             - v2-lfs-master
       - shell:
           name: Pull Git LFS files, retry until done
           command: |
             while true; do git reset --hard HEAD && git clean -fd && git lfs pull && break; done
       - save_cache:
          key: v2-lfs-{{ .Branch }}
          paths:
            - .git/lfs
       - restore_cache:
           keys:
             - v5-deps-{{ arch }}-{{ checksum "SetupThrive.rb" }}
             - v5-deps-{{ arch }}
       - restore_cache:
           keys:
             - v5-build-{{ arch }}-{{ .Branch }}
       - run: ./SetupThrive.rb --no-packagemanager --no-updates --precompiled -j 2 --fully-parallel-project-compile --project-parallel 5
       - save_cache:
           key: v5-deps-{{ arch }}-{{ checksum "SetupThrive.rb" }}
           paths:
             - ThirdParty
       - save_cache:
           key: v5-deps-{{ arch }}
           paths:
             - ThirdParty
       - save_cache:
           key: v5-build-{{ arch }}-{{ .Branch }}
           paths:
             - build/src
       - run: mkdir -p /reports/reports
       - run:
           command: ./ThriveTest "~[xrequired]"
           working_directory: ~/thrive/build/bin
       # - run:
       #     command: ./LeviathanTest --reporter junit --out /reports/reports/test_run.xml "~[xrequired]"
       #     working_directory: ~/leviathan/build/bin
       # - store_test_results:
       #     path: /reports/reports
   format_script:
     working_directory: ~/Thrive
     docker:
       - image: hhyyrylainen/thrive-deps:v1
     steps:
       - checkout
       # eslint is completely silly in refusing to use a globally installed plugin
       - restore_cache:
           keys:
             - v1-npm-{{ checksum ".eslintrc.js" }}       
       - run: npm install eslint-plugin-html@latest --save-dev
       - save_cache:
           key: v1-npm-{{ checksum ".eslintrc.js" }}
           paths:
             - node_modules
       - run: ./RunCodeFormatting.rb
       - run:
           when: always
           command: |
             git diff > format_diff.patch
             if grep -q '[^[:space:]]' < format_diff.patch; then
                 echo "Formatter found things to be fixed:"
                 cat format_diff.patch
                 exit 1
             else
                 echo "No changes made"
                 rm -f format_diff.patch
             fi
       - store_artifacts:
          path: format_diff.patch


workflows:
  version: 2
  build_and_format:
    jobs:
      - build
      - format_script
