version: 2
jobs:
   build:
     working_directory: ~/Thrive
     docker:
       - image: hhyyrylainen/godot-ci:v1
     environment:
       GIT_LFS_SKIP_SMUDGE: 1
     steps:
       - checkout
       - restore_cache:
           keys:
             - v4-lfs-{{ .Branch }}
             - v4-lfs-master
       - shell:
           name: Pull Git LFS files, retry until done
           command: |
             while true; do git reset --hard HEAD && git clean -fd && git lfs pull && break; done
       - save_cache:
          key: v4-lfs-{{ .Branch }}
          paths:
            - .git/lfs
       - restore_cache:
           keys:
             - v2-import-{{ .Branch }}
             - v2-import-master
       - run: mkdir -p builds
       # This is here to reimport assets, but this build would fail due to missing nuget packages
       # if C# was compiled here
       - run: godot --export "Linux/X11" "builds/a.x86_64"
       - run: ./headless_project_refresh.rb
       - save_cache:
           key: v2-import-{{ .Branch }}
           paths:
             - .import
       - restore_cache:
           keys:
             - v1-nuget-{{ .Branch }}
       - run: nuget restore Thrive.sln
       - save_cache:
          key: v1-nuget-{{ .Branch }}
          paths:
            - ~/.nuget/packages
       # Format check before making final packages
       - run: ./check_formatting.rb
       # Proper packages
       - run: godot --export "Linux/X11" "builds/thrive_linux.x86_64"
   # format_script:
   #   working_directory: ~/Thrive
   #   docker:
   #     - image: hhyyrylainen/godot-ci:v1
   #   environment:
   #     GIT_LFS_SKIP_SMUDGE: 1
   #   steps:
   #     - checkout
   #     - run: ./headless_project_refresh.rb
   #     - restore_cache:
   #         keys:
   #           - v1-nuget-{{ .Branch }}
   #     - run: nuget restore
   #     - save_cache:
   #        key: v1-nuget-{{ .Branch }}
   #        paths:
   #          - ~/.nuget/packages
   #     - run: ./check_formatting.rb

workflows:
  version: 2
  build_and_format:
    # Unfortunately godot is setup so that a build can't happen without having all the assets processed
    jobs:
      - build
      # - format_script
